### ISSUE TITLE
Make it Borealis, Basilisk and/or toolkit compatible

### ISSUE THREAD

**Issue by wolfbeast** [JustOff/github-wc-polyfill#1]
All UXP applications could benefit from this, so you should make it compatible with them in install.rdf

**Comment by JustOff** [comment]
I'll add Basilisk as you think it's important, but Borealis can only be considered when it's no longer hidden source project.

**Comment by wolfbeast** [comment]
Thanks for adding Basilisk support.

> when it's no longer hidden source project.

You could always just add the toolkit ID as a target application to cover all UXP-based browsers that could benefit from this, but I'll leave that decision up to you.
