### ISSUE TITLE
ShadowRoot is not defined

### ISSUE THREAD

**Issue by lollita** [JustOff/github-wc-polyfill#11]
In Browser console I see:

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!  36374
> ReferenceError: ShadowRoot is not defined[Learn More]

Do it is normal?

**Comment by JustOff** [comment]
No, it's not. Please provide the details on how to reproduce the issue using a fresh profile with only github-wc-polyfill installed.

**Comment by FrozenVoid** [comment]
I get a different error(mentioned in the CPU overload thread https://github.com/JustOff/github-wc-polyfill/issues/10#issuecomment-737686892 ) "ReferenceError: queueMicrotask is not defined[Learn More]"
probably both are connected with WebComponents being used before they load.

**Comment by JustOff** [comment]
Whether it's true or not, I still need steps to reproduce.

**Comment by FrozenVoid** [comment]
CSP errors are gone with 1.1.7

**Comment by JustOff** [comment]
This is great, but has nothing to do with the still unconfirmed issue discussed here.

**Comment by JustOff** [comment]
Feel free to reopen when steps to reproduce are available.
