### ISSUE TITLE
Не работает в Firefox ESR 52.9.0

### ISSUE THREAD

**Issue by Baltazar500** [JustOff/github-wc-polyfill#12]
Время от времени дополнение не срабатывает и на гитхабе продолжают наблюдаться серые прямоугольники вместо текста как тут например https://github.com/sunjw/jstoolnpp/tree/master/sub-proj

![p5BZlHZcpmN3KaU63JJUybXR7db](https://user-images.githubusercontent.com/12525093/103296490-eaf22700-4a41-11eb-8087-c48afc26d8e6.jpg)

p.s. Посредством этого дополнения можно решить вопрос с просмотром превью на гитхабе (кнопка превью заработала, но превью не появилось - "Nothing to preview") и аттачем файлов ? Или для этого нужны другие костыли ?

**Comment by Vangelis66** [comment]
Hello :smiley: 

Though, no doubt, the extension's maintaner is fluent in Russian, as a general courtesy to the rest of the people _watching this repo_, it would be welcome to also post in **English** (e.g. via a translation service, if not able yourself... ).

Machine translation: 
```
The add-on does not always work on GitHub and gray rectangles continue to be displayed instead of text. #12

From time to time, the add-on does not work and gray rectangles continue to be observed on GitHub 
instead of text, as here for example: 
https://github.com/sunjw/jstoolnpp/tree/master/sub-proj

-- img attachment --

PS: With this add-on, can you solve the issues with 
1) viewing the preview on github (the preview button works, but the preview itself does not appear -> 'Nothing to preview') and 
2) attaching files? 
Or do you need other crutches (?) for this?
```

You are giving absolutely NO details as to the **_version_ of the browser used, the _platform_ it builds on and the _OS_ it is running on**... :-1: 

If I may comment on the `Nothing to preview` issue, **the browser and its platform need support the Abort API** for it to function; **recent UXP** versions (Pale Moon, Basilisk, Mypal etc.) will be fine, but if you're still stuck on **Fx ESR 52.9.x** (on XP/Vista), then that GitHub feature will fail, despite having this extension installed... :disappointed: 

Kind regards, festive wishes

**Comment by JustOff** [comment]
Имя и версия браузера, ОС? Воспроизводится ли в чистом профиле, когда github-wc-polyfill единственное расширение?

**Comment by Baltazar500** [comment]
@Vangelis66,

>Though, no doubt, the extension's maintaner is fluent in Russian, as a general courtesy to the rest of the people watching this repo, it would be welcome to also post in English (e.g. via a translation service, if not able yourself... ).

Мой английский на пару с гугло-переводчиком оставляет желать лучшего и составление корректных запросов отнимает у меня слишком много сил и времени, которые просто бесмысленны, учитывая тот факт, что разработчик общается на русском. А использование машинного перевода в чистом виде мне видится мне куда большим неуважением к пользователям, нежели создание запросов на родном языке. Особенно, если это может создать недопонимание с обеих сторон.

###Machine translation:

My English paired with a google-translator leaves much to be desired and making correct requests takes too much time and effort from me, which are simply pointless, given the fact that the developer speaks Russian. And the use of machine translation in its purest form seems to me to be much more disrespectful to users than creating queries in their native language. Especially if it can create misunderstandings on both sides.
@JustOff, 

>Имя и версия браузера, ОС? Воспроизводится ли в чистом профиле, когда github-wc-polyfill единственное расширение?

Mozilla Firefox ESR 52.9.0 x64, WIN 7 X64 SP1. Воспроизведение проблемы на чистом профиле не проверял. Буду смотреть.

**Comment by Vangelis66** [comment]
@Baltazar500 

Thanks for your explanation and effort... 😄 

> Mozilla Firefox ESR 52.9.0 x64

... Just as I had suspected!

>> if you're still stuck on FxESR 52.9.x (snipped) 
then _**that**_ GitHub feature will fail, 
despite having this extension installed...

You _must_ have your own reasons for staying with **FxESR 52** on **Win7** SP1 (for which numerous choices of current/updated browsers are available (unlike in XP/Vista 😭 ), all of which support GitHub _natively_), but, as I said, the `Preview` feature on GitHub **relies on the Abort API** (aka [abortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)) being available in the browser engine, which is NOT the case for **FxESR 52** 😞 ...

It _might_ be possible to transplant that API in Fx52 via another polyfill, but only @JustOff will know for sure...

Kindest regards

**Comment by JustOff** [comment]
Сорри, но Firefox ESR 52.9.0 не поддерживается - там просто нет необходимы компонент для работы GitHub.

**Comment by Baltazar500** [comment]
@Vangelis66, thanks for your reply ;)

@JustOff,

>Сорри, но Firefox ESR 52.9.0 не поддерживается

Понятно. Потому и работает через раз. Прямоугольники вылезают сейчас нечасто. Без него бы было совсем туго.

>там просто нет необходимы компонент для работы GitHub.

А в какие браузеры на gecko порекомендуете ставить ?

**Comment by micwoj92** [comment]
> 
> А в какие браузеры на gecko порекомендуете ставить ?

With windows 7 you probably can still use latest Firefox 84 but if you don't want I would recommend either Basilisk or Pale Moon.

**Comment by JustOff** [comment]
> в какие браузеры на gecko порекомендуете ставить ?

Соглашусь с советом выше, лично я использую оба Firefox и Pale Moon, в зависимости от задачи.
