### ISSUE TITLE
Load more... loads a blank more_items page

### ISSUE THREAD

**Issue by biopsin** [JustOff/github-wc-polyfill#13]
Heya,
seems there is a issue when trying to expand those hidden items
```
~~~~[xx hidden items]~~~ 
       Load more...
```
example bellow:
 `https://github.com/void-linux/void-packages/pull/24258#issuecomment-676269285`

page opening on "Load more.."
https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0NDY3NDczMDU4/timeline/more_items
is just blank.

**Comment by JustOff** [comment]
Can't reproduce this, everything works just fine for me.

Please provide the details about your browser, version and OS.
Does it work in a clean profile with only `github-wc-polyfill` installed?

**Comment by biopsin** [comment]
Pale Moon 28.17.0 on voidlinux-x86_64 glibc-2.30
Tested with clean profile too, but did not notice;

Error console
> Timestamp: 12/30/2020 02:08:44 PM
> Error: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
> Source File: https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0NDY3NDczMDU4/timeline/more_items
> Line: 0

Ok, so it's a local issue i guess, sorry for the fuzz..
I have fallback character encoding set to UTF-8, so I'm not shure why this is cropping up now..

**Comment by JustOff** [comment]
An error with undeclared encoding when you try to load hidden comments occurs if the extension is not installed at all or does not work. Please double-check your test environment and any other errors in the console. Also, are you using the official Pale Moon build?

**Comment by biopsin** [comment]
I persume it's working or I would not be able to do many operations without it.
It's the only error I notice in console at this present time and also after many hours spent on github.
Custom build, but will have to check against the official. 
Thank you for your time JustOff, hope you will have a pleasant new year's eve.
