### ISSUE TITLE
github - color labels

### ISSUE THREAD

**Issue by AroKol78** [JustOff/github-wc-polyfill#14]
(translation Polish>English)
I don't know if this is a good place to submit - I'm using "github-wc-polyfill"
**some labels are illegible (black text on dark color)**
if you find it irrelevant, just close my application
thanks for the addon "github-wc-polyfill"

(original Polish)
nie wiem czy to dobre miejsce na zgłoszenie - używam "github-wc-polyfill"
**niektóre etykiet są nieczytelne (czarny tekst na ciemnym kolorze)**
jeśli uznasz to za nieistotne to po prostu zamknij moje zgłoszenie
dziękuje za dodatek "github-wc-polyfill"

screenshot of `https://github.com/AdguardTeam/AdguardFilters/issues`
![gihabbugcol](https://user-images.githubusercontent.com/70756447/103678992-8fb1be80-4f84-11eb-8a54-0e1b9df51015.PNG)

**Comment by JustOff** [comment]
Unfortunately, I don't know how to fix it properly, but even if I did, I'm not sure if it should be part of this extension.

As for now, you can take a look at some of the workarounds discussed [there](https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-753672342).

**Comment by AroKol78** [comment]
thanks **krystian3w** , **THEtomaso**
now you can test colors labels globally (love hex)
`github.com##[class*="Label" i]:style(color: #ff7777 !important;)`
