### ISSUE TITLE
none sha512

### ISSUE THREAD

**Issue by AroKol78** [JustOff/github-wc-polyfill#17]
on "github" pages (UXP last build ,github-wc-polyfill last)
Error Console : `None of the “sha512” hashes in the integrity attribute match the content of the subresource.`
please add sha512 support
is it possible to support sha512

**Comment by JustOff** [comment]
Please specify the browser, version and page where you see this error.

**Comment by AroKol78** [comment]
"MoonchildProductions / UXP  - February 5, 2021" (browser custom)
and my seting `security.tls.version.min 3` , maybe other settings also matter

![buggithb01](https://user-images.githubusercontent.com/70756447/109387845-f0fe6a00-7903-11eb-8191-10c112b9bc26.PNG)

**Comment by JustOff** [comment]
Sorry, but I can hardly help you until you provide a sequence of steps to reproduce the error in a clean profile using the official Pale Moon or Basilisk build.

**Comment by AroKol78** [comment]
I never use a clean profile (settings for added security)
browser custom = then I know what I'm using
it is not known what is in the code official browser - they might have hidden something
(nobody can be trusted these days)

**Comment by AroKol78** [comment]
similar for "none sha512"
`https://github.community/t/github-consuming-100-of-cpu-core-wont-relinquish-unless-entire-browser-closed/168703`
`https://forum.palemoon.org/viewtopic.php?p=211107#p211107`

i am using Win - no problem with scrolling , no problem with cpu load
(example - i don't see this error on youtube or the scrolling error)

possible problem with the browser engine (UXP - Win/Lin)
