### ISSUE TITLE
taking too long to load

### ISSUE THREAD

**Issue by AroKol78** [JustOff/github-wc-polyfill#20]
entry `https://github.com/AdguardTeam/AdguardFilters`  **without logging in**  (when i am logged in it works fine)
choose
`issues`
`Sort by - Recently updated`
`issues - closed`
= error displays
unicorn
This page is taking too long to load.
Sorry about that. Please try refreshing and contact us if the problem persists.

**Comment by JustOff** [comment]
GitHub has different limits for queries from authorized and anonymous users, this doesn't depend on the browser or extension.
