### ISSUE TITLE
Modify minVersion

### ISSUE THREAD

**Issue by luweitest** [JustOff/github-wc-polyfill#21]
I use Serpent52, which is a fork of Basilisk, whose version number is always 52.9.0. In order to make the add-on work, the version requirements line in the install.rdf should be modified to: `<em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
        <em:minVersion>52.9</em:minVersion>
`

**Comment by JustOff** [comment]
Sorry, but no, otherwise it will mislead users of the original Firefox, where this extension doesn't fix the incorrect operation of GitHub.
