### ISSUE TITLE
TypeError: e.getRootNode is not a function

### ISSUE THREAD

**Issue by hawkeye116477** [JustOff/github-wc-polyfill#22]
For example go to https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/actions/runs/739397149 and click `See more`.
Nothing happens and on console I see `TypeError: e.getRootNode is not a function`.

Browser: Basilisk 2021.03.17

**Comment by AroKol78** [comment]
`https://github.githubassets.com/assets/chunk-vendor-8484e564.js` line:148

**Comment by JustOff** [comment]
Yep, and if you set `dom.getRootNode.enabled -> true` leads to `ReferenceError: ShadowRoot is not defined`.

This requires further research, it's probably worth trying to use [get-root-node-polyfill](https://github.com/foobarhq/get-root-node-polyfill).

**Comment by JustOff** [comment]
Well, [get-root-node-polyfill](https://github.com/foobarhq/get-root-node-polyfill) gives the same `ReferenceError: ShadowRoot is not defined`.

It seems we need to polifill `ShadowRoot` as well, see also https://github.com/JustOff/github-wc-polyfill/issues/19#issuecomment-804382679.

**Comment by JustOff** [comment]
Looks like that [webcomponentsjs](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs) polyfills do not help either. I'm stuck around this point ...

**Comment by dirkf** [comment]
Presumably you tried replacing the [minified CE polyfill](https://github.com/JustOff/github-wc-polyfill/blob/bc12817aa8093e4d79b0306d29b5cba7a8382031/bootstrap.js#L143) with one derived from https://github.com/webcomponents/polyfills/blob/master/packages/webcomponentsjs/src/entrypoints/webcomponents-sd-ce-index.js?

With either my non-functional ShadowDom facade or https://cdnjs.cloudflare.com/ajax/libs/shadydom/1.8.0/shadydom.min.js (includes `getRootNode()`), I don't see any errors, but OP's link does nothing (not even posting an error to GitHub, as happens with no SD).
