### ISSUE TITLE
Youtube Polyfill

### ISSUE THREAD

**Issue by ReNardier** [JustOff/github-wc-polyfill#24]
i think it might be acting up, since about half a month ago youtube keeps freezing by doing things such as putting your mouse such that the little text bubble that says "search" appears, or by being on tab 1 and having youtube on tab 2(the tab bar looks such: 1 2) and then closing 1 making you enter the youtube tab, i have had to restart my computer because that locked it up, i think is the polyfill because some dude on the palemoon forums managed(after many times) to get an error message and it mointed to the polyfill
thanks in advance

**Comment by JustOff** [comment]
Please provide the steps to reproduce this issue using a new, unmodified browser profile where GitHub Web Components Polyfill is the only extension.

**Comment by JustOff** [comment]
The required information is not provided by the reporter.
