### ISSUE TITLE
Blocking remote fonts with uBlock Origin breaks gitlab

### ISSUE THREAD

**Issue by JustOff** [JustOff/github-wc-polyfill#26]
See https://github.com/gorhill/uBlock-for-firefox-legacy/issues/311.

**Comment by JustOff** [comment]
@l29ah, please try [github-wc-polyfill-1.2.3b1.xpi](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.2/github-wc-polyfill-1.2.3b1.xpi).

**Comment by l29ah** [comment]
Thanks, it works now.
