### ISSUE TITLE
Palemoon devs going loco - what will the alternatives be?

### ISSUE THREAD

**Issue by rubyFeedback** [JustOff/github-wc-polyfill#32]
This is not necessarily concerning github-wc-polyfill but a more general issue or question.

I just dug through the history of the 3 main palemoon devs and I am pretty shocked,
including their behaviour on the webforum or sneakily modifying extensions without
announcing this. But, skipping these 3 epic trolls, what alternatives do we have? 
Will we be forced back into the Google empire? I am still using palemoon right now
mostly due to inertia, but I am not going to waste my time with the 3 insane palemoon
core devs anymore (Tobin is the nuttiest among these three by far really).

IF you have suggestions it would be useful if you could perhaps mention them in
some of the github repositories so people can check. I am also banned from the
palemoon forum - Moonchild can not take criticism. Dude has some mental issue.

So the TL;DR: please consider linking to viable alternatives in particular aside
from chrome and firefox if you know about them. Thanks for reading.

**Comment by JustOff** [comment]
Thank you for sharing your thoughts, but obviously this is offtopic here.
