### ISSUE TITLE
notifications checkmark button doesn't work anymore

### ISSUE THREAD

**Issue by rofl0r** [JustOff/github-wc-polyfill#34]
when clicking in notifications the button with the checkmark (to mark a notification as processed), one gets redirected to empty page https://github.com/notifications/beta/archive.
i guess they changed some stuff again.
using latest release as published 3-4 days ago

**Comment by JustOff** [comment]
Browser/version? Errors in console?

**Comment by rofl0r** [comment]
pm 29.3.0
i'll look for console errors next time i get a notification i don't wanna read

**Comment by rofl0r** [comment]
i just clicked away this notification and it worked. probably need to wait until a couple accumulate and then click away non-top one

> It would also be useful if you could reproduce the issue with the latest pm version (29.4.1) in a clean profile (for example, using a portable).

i'm building PM from source and when 29.4.x came out i checked changes in git and there wasn't anything that seemed important (and 29.4.1 is basically almost identical to 29.3.0 as it just undid 2 major changes coming with 29.4.0)

> You can always move any notification back to inbox and then mark it as unread.

ok, might try that instead.

either way i suspect more reports will pop up soon.

**Comment by rofl0r** [comment]
ok, by clicking on non-top one i could reproduce

console has this:
> Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.

> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

**Comment by JustOff** [comment]
I see no point to keep this open as no one else confirmed this issue for 18 days.

**Comment by rofl0r** [comment]
true.dat, i haven't encountered this again, so i was probably victim of A/B testing.
