### ISSUE TITLE
GitLab (Next) now broken in UXP-based browsers :-(

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#37]
I've thanked you many times 👍 for creating and maintaining this **excellent extension**, without which **UXP-based** browsers (_official_ releases and _forks_ alike 😉 ) would be rendered useless for **GitHub**/**GitLab** frequenters... Let this be once more... 😄 

Browser: **Serpent 52.9.0 (32-bit)**, buildID=**20211008**025107
**NB**: Its UXP platform should be on par/better than the latest official **Basilisk 52.9.2021.09.27 (64-bit)** release...
Extension version: **1.2.7** (latest)

When one visits a GitLab URL, _by default_ one's being served the "GitLab **Next**" rendition of that URL: 

![GLNext_logo](https://user-images.githubusercontent.com/9669492/140237758-d43e3a8d-c359-468b-bfa4-52f0ad70a12a.jpg)

Until a few days ago, `v1.2.7` of `github-wc-polyfill` had no issues working its wonders on **GL Next** pages, however, this isn't true any more... 😭 E.g., upon loading

https://gitlab.com/gitlab-org/gitlab/-/issues/333598

I get: 

![GLNext](https://user-images.githubusercontent.com/9669492/140238119-1250e216-a689-4c91-b856-9f4d6dac936a.JPG)

By the looks of it, this is a repetition of #28, i.e. they're again pushing **newer RegExp syntax that isn't palatable to current UXP**... 👎 😞 😠 

I'm not sure whether this new breakage could be fixed inside the extension (a la #28) and, personally, am losing faith this cat-and-mouse game can go on for much longer... With what's been going on lately in MCP-land and GitLab's determination to bow down willy-nilly to what Google Chrome implements, things look grim... 😿 

INTERIM WORKAROUND: 

"**Current**" GitLab appears to work fine with  `github-wc-polyfill-1.2.7`, at least at the time of this writing; 
you can opt to revert to **Current** when visiting GL pages by loading
https://next.gitlab.com/
and moving the slider to the left; your selection is stored in a browser cookie named `gitlab_canary`, its content value should be `false`; I've used a browser extension (CookieKeeper 1.9.3.1) to prolong that cookie's expiration time and also "protect" it, 
![CKGL](https://user-images.githubusercontent.com/9669492/140240575-7386b3f8-43d2-42fc-bd66-7a80706d58e7.JPG)
so, thankfully, I'm now getting a compatible GitLab iteration... Prone to future breakage, sadly, when they
a. break "**Current**" even more... 😞 
b. retire "**Current**" completely, when _current_ "**Next**" becomes the "**Current**" of the future... :angry:

**Comment by JustOff** [comment]
The culprit is [Unicode property escapes](https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes), added here:
- https://gitlab.com/gitlab-org/gitlab-ui/-/merge_requests/2458
- https://gitlab.com/gitlab-org/gitlab-ui/-/commit/d23c341bb8cef5683bf2d49556dabe4008be76cf

Possible workaround is to replace `\p{Emoji}` with an emojis list, using something like this:
- https://stackoverflow.com/questions/43242440/javascript-regular-expression-for-unicode-emoji

**Comment by Vangelis66** [comment]
Belated thanks for the prompt response and almost instantaneous fix! 🎉 👍 ; I tested in a new _ContainerTab_ in **St52** (so that my protected `gitlab_canary` cookie does not come into play) and the **GL Next** page loaded as expected! Sterling job!

![GLFIX](https://user-images.githubusercontent.com/9669492/140619593-4f6f7e4d-d996-41ca-a30e-b228c6f9d62c.JPG)

... Apologies for sounding somewhat pessimistic in my original report 😉 ; this was in no way an indirect questioning of your coding expertise 😄  but a reflection of the general feeling I harbour regarding the future of "legacy" web-engines; a feeling that was compounded more by the realisation **GL devs** would break them in an instance **for the sake of emoji rendering** (😠), by implementing code only supported in Fx**78**+ ... 
 Guess emojis today, in the **social-media** governed web, take precedence over actual page content :rage: (says one who uses emojis on GitHub, too :smile: ...).

**Comment by JustOff** [comment]
You have nothing to apologize for, it's obvious that if something does not develop, then it dies, and this polyfill is just a palliative.

**Comment by Elias011980** [comment]
This bug is back with a vengeance on this site:
https://git.alchemyviewer.org/alchemy/
A new Emoji ?

**Comment by JustOff** [comment]
@Elias011980, see https://github.com/JustOff/github-wc-polyfill/releases/tag/1.2.9.

**Comment by Elias011980** [comment]
> @Elias011980, see https://github.com/JustOff/github-wc-polyfill/releases/tag/1.2.9.

Yep, that works, thanks!

Perhaps, however, would it be a good idea to find a better way to detect github/gitlab sites than by their base URL, assuming it is at all possible...

**Comment by JustOff** [comment]
I'm afraid that automatic detection of sites where polyfill is required is hardly possible without noticeable performance degradation.

**Comment by l29ah** [comment]
https://0xacab.org/leap/bitmask-vpn doesn't work too, plz kludge in!

**Comment by Elias011980** [comment]
> I'm afraid that automatic detection of sites where polyfill is required is hardly possible without noticeable performance degradation.

Then perhaps allowing to add new domains to the list via an extension setting (instead of relying on extension updates) ?

**Comment by JustOff** [comment]
> https://0xacab.org/leap/bitmask-vpn doesn't work too, plz kludge in!

It's already [there](https://github.com/JustOff/github-wc-polyfill/blob/7dc122dadca0d103a6485c830eda44232e851aad/make_glmask.js#L2), but, as far as I can see, that server uses customized server code and a special security policy.
Try this beta: [github-wc-polyfill-1.2.10b1.xpi.zip](https://github.com/JustOff/github-wc-polyfill/files/7722144/github-wc-polyfill-1.2.10b1.xpi.zip) (rename to xpi to install).

> Then perhaps allowing to add new domains to the list via an extension setting (instead of relying on extension updates) ?

Perhaps someday)

**Comment by jeberger** [comment]
> > Then perhaps allowing to add new domains to the list via an extension setting (instead of relying on extension updates) ?
> 
> Perhaps someday)
This would be especially useful for private instances. E.g. in my company we use an internal Gitlab instance, but I can hardly expect you to add the URL of every company private instance out there 😉
