### ISSUE TITLE
It does not work in the Light browser

### ISSUE THREAD

**Issue by arteze** [JustOff/github-wc-polyfill#38]
When installing the extension in the __Light__ browser, an error comes out.

> GitHub/GitLab Web Components Pollyfill could not be installed because it is not compatible with Light 48.0.

Is there any solution? Right now I'm in __Github__ in __Light__, and it does not completely charge well.

**Comment by JustOff** [comment]
I don't know what the Light browser is, but this extension supports only UXP-based browsers and SeaMonkey.

**Comment by arteze** [comment]
The Light browser is an Firefox fork.

 - https://en.wikipedia.org/wiki/Light_(web_browser)

I managed to make the extension be installed, changing the `<em:maxVersion>` to 50.*.

Even though the extension appears load, it does not work.

**Comment by micwoj92** [comment]
Last release was 5 years ago, it is basically abandonware.

**Comment by arteze** [comment]
@micwoj92 I understand ... uBlock Legacy works, but this extension of the Polyfill does not work, and I do not know why, one works and this extension, no.

**Comment by micwoj92** [comment]
This extension doesnt work on firefox 52.9 so it wont work on any version that was released prior. I dont know any technicalities but similar tickets have been closed in past.
https://github.com/JustOff/github-wc-polyfill/issues/12
https://github.com/JustOff/github-wc-polyfill/issues/21

**Comment by Vangelis66** [comment]
> uBlock Legacy works, but this extension of the Polyfill does not work, 
> and **I do not know why**, one works and this extension, no.

With respect, you're "comparing apples with oranges", both **fruits**, but **very different from each other**...

There is no logical consequence that if **uBO-legacy** works, so should **gh-wc-p**; FWIW, minimum requirements for the **former** is **Mozilla Firefox 45.0 platform**, and this proviso is fulfilled by your deprecated/abandonware browser (reportedly based on **48.0** platform); gh-wc-p is a totally different extension and demands recent **UXP platform** versions (and/or SM 2.53.x) to be able to work as planned... 

Force-installing the extension on an incompatible browser engine will get you nowhere, as you've already found out the hard-way... The underlying application platform needs to **support certain Web APIs** that are crucial for the correct functioning of the GH-polyfills this extension makes possible to load... 
Hope it's more clear to you now... 😉

**Comment by arteze** [comment]
@Vangelis66 I understand it better, I'll see if I can make it work in Light.

**Comment by Vangelis66** [comment]
> I'll see if **I can make it work in Light**

... As stated _multiple times by multiple people_ here, IT'S NOT POSSIBLE TO...
You provide no clues as to your setup, other than the use of this **deprecated Fx48.0 fork**; 
migrate to one of the **UXP-based** browsers (Pale Moon 29.x.x, Basilisk 52.9.2021.11.14[x64]) to use the extension properly; if you're not up-to **Windows 7 SP1** already, some forks of the above do exist that we'll run on XP/Vista (but let's cross that bridge when needed...). 

The fact you still think you can make it work under a Moz 48.0 platform indicates that 
a) you still don't fully understand
b) you're somehow a browser wizard! 😉 

I'll refrain from posting further, unless _absolutely needed_, for fear of derailing this already "closed/invalid/can't fix" issue...

**Comment by arteze** [comment]
Well, I will leave anyway the message to clarify what I was thinking. 

Yes, I understood the message, but if I edit the code that works from uBlock Origin and I am removing things, then I could insert the Polyfill code, I wanted to refer to that.

In case of not working, I have my own compilation of functions to create a Polyfill, who could also use it in the addon.
