### ISSUE TITLE
wheels-github

### ISSUE THREAD

**Issue by AroKol78** [JustOff/github-wc-polyfill#41]
e.g. https://github.com/JustOff
spinning wheels
![bugokrog00](https://user-images.githubusercontent.com/70756447/146457029-42ba075e-1c58-49b0-a64b-ec1010979a03.PNG)

**Comment by AroKol78** [comment]
the top wheel had repaired itself
larger circles remain (maybe it will repair itself too)

**Comment by JustOff** [comment]
At the moment I see the same issue on Chrome and Firefox.

**Comment by AroKol78** [comment]
https://github.com/AroKol78
![haha02](https://user-images.githubusercontent.com/70756447/146542357-50503c54-8eb8-4554-a291-0a292c6622e5.PNG)

**Comment by JustOff** [comment]
I'd rather wait until they fix this on the server side.

**Comment by AroKol78** [comment]
he fixed himself - it's ok
