### ISSUE TITLE
gitlab login does not work

### ISSUE THREAD

**Issue by mittorn** [JustOff/github-wc-polyfill#42]
Server just return 422 error when trying to login to any gitlab instance

**Comment by JustOff** [comment]
Unable to reproduce this issue using an unknown version of an unknown browser with unknown settings.

**Comment by mittorn** [comment]
Recent Pale Moon with 1.2.9 has this issue at least, not tried with seamonkey. Any social button results in 422 error
scriptlet doctor does not change behaviour. I tried waterfox classic, it has the same behaviour. Recent waterfox is building now, so i cannot  check it, binary waterfox-g4 builds crashes on my system. Maybe it is depended on ISP? i have ipv6 enabled

**Comment by JustOff** [comment]
In Pale Moon 29.4.4 I can sign in to GitLab either via email and password or using GitHub as an OAuth2 provider.
You should try a new clean profile with default settings and only `github-wc-polyfil` installed.

**Comment by mittorn** [comment]
Clean profile with only github-wc-polyfill still results in 422 error

**Comment by mittorn** [comment]
Waterfox-G4 still gets 422, so i sure it's ISP issue

**Comment by JustOff** [comment]
Well, ok then.
