### ISSUE TITLE
GitHub is broken because of using ECMAScript2020/2021 features

### ISSUE THREAD

**Issue by AroKol78** [JustOff/github-wc-polyfill#43]
many things don't work (sending pictures, ...)

![firefox_2022-02-11_00-37-22](https://user-images.githubusercontent.com/340855/153508596-f05c2aa6-9585-4505-aa94-b6a66143bc5d.png)

**Comment by roytam1** [comment]
it uses new javascript syntax now

**Comment by RamonUnch** [comment]
Hopefully there are some workarounds

**Comment by JustOff** [comment]
There will be no workarounds until the issue isn't described properly, including steps to reproduce and what exactly goes wrong.

**Comment by AroKol78** [comment]
I don't know what I need to fix the bugs (last edition Serpent52/UXP)
don't work: editing comments, sending pictures, buttons ("Show more activity","Edit profile",...), profile menu, recent activity, ...

**Comment by rofl0r** [comment]
i wonder if it would be possible to build something like https://github.com/babel/babel into palemoon which automatically transpiles all incoming js to the version it supports before executing it.

**Comment by garoto** [comment]
> Well, the problem is optional chaining (?.) operator introduced in Firerox 74, see https://bugzil.la/1566143.

Is this something "workaroundable" without too much hassle?

**Comment by rofl0r** [comment]
this is quite a deal breaker. can't even create a release from a tag anymore.

**Comment by hiiamboris** [comment]
poor bastards just can't stop breaking things

**Comment by garoto** [comment]
In the meanwhile, I've being watching a YT series of videos where the main developer of SerenityOS tries to implement Discord "webapp" compatibility in the OS native browser from scratch and its a fascinating watch, even though I'm not a computer programmer at all, but I have a good grasp on all the premises and concepts and whatnot.

**Comment by garoto** [comment]
(since I can't edit my post above because "edit" is broken) It's also a nice parallel to the state of Palemoon currently and in general.

**Comment by Symbian9** [comment]
@garoto, You can still pick your reaction to GitHub comments with Pale Moon, so not all is bad... yet ;)

**Comment by garoto** [comment]
Like so after a full page refresh? lol. 

I'm starting to think its time for me to "move on", it's all getting really tiresome...

**Comment by Symbian9** [comment]
> I'm starting to think its time for me to "move on", it's all getting really tiresome...

Yeah, its good time to move from GitHub:

- to https://gitlab.com
- to https://codeberg.org
- to https://notabug.org
- to https://git.je
- to https://launchpad.net
- to https://sourceforge.net
- to self-hosetd GitLab, Gitea, etc.

**Comment by garoto** [comment]
lol, to be honest, everything you listed is "hot garbage". 

gitlab? c'mon now... "IF" I was looking for a place to host software, it'd be at sourchut's (https://sr.ht).

**Comment by garoto** [comment]
But I guess you're only posting this garbage because "omg, microsoft bought github!!1". github is the same garbage webiste now as it was before the mega-software-conglomerate aquisition.

The only difference in 2022 is that now they have 30+ employees more with colored hair while living in the SF streets like hobos.

**Comment by SeaHOH** [comment]
Change the `User-Agent` version's number below v74 is a temporary relief:

    name: general.useragent.override.github.com
    value: Mozilla/5.0 (%OS_SLICE% rv:68.9) Gecko/20100101 Firefox/68.9 PaleMoon/28.17.0

**Comment by dirkf** [comment]
I "reached out" to GH and they **reverted the change**. I haven't checked whether they're serving optional chaining to their supported browser versions and only reverting for other UAs, which I suggested as an option.

**Comment by mh3663** [comment]
> I "reached out" to GH and they **reverted the change**. I haven't checked whether they're serving optional chaining to their supported browser versions and only reverting for other UAs, which I suggested as an option.

As a SeaMonkey enthusiast and lurker on the a.c.s.seamonkey newsgroup, I applaud you.
Cheers!

**Comment by Symbian9** [comment]
> I "reached out" to GH and they reverted the change.

@dirkf, WOW! You emailed them or there is public issue thread on this?

**Comment by JustOff** [comment]
They reverted the libs for all browsers, so I'm afraid that it's only temporarily and will not last long.

**Comment by Symbian9** [comment]
> Also, just compare these two lines

Just a correction, two lines should be in code block:

```
o=(r=(e=t.head)==null?void 0:e.querySelector('meta[name="expected-hostname"]'))==null?void 0:r.content;
e=t.head?.querySelector('meta[name="expected-hostname"]')?.content;
```

**Comment by rofl0r** [comment]
interesting. previous requests like this were ignored by gh management, maybe it's got to do with you being a youtube-dl contributor.

**Comment by AroKol78** [comment]
the same problems came back as I wrote earlier

**Comment by dirkf** [comment]
[Deprecation Notice for ECMAScript2020 Support](https://github.blog/changelog/2022-02-10-deperecation-notice-for-ecmascript2020-support/)

But they seem to have jumped the gun.

**Comment by JustOff** [comment]
Well, at the moment GitHub does not work even in Firefox 78 ESR. This means that our chances for a workaround tend to zero.

**Comment by AroKol78** [comment]
>Deprecation Notice for ECMAScript2020 Support
 GitHub.com but with limited functionality

can't even handle the basics of things
>..."Show more activity","Edit profile",...), profile menu,...

**Comment by SeaHOH** [comment]
> [Deprecation Notice for ECMAScript2020 Support](https://github.blog/changelog/2022-02-10-deperecation-notice-for-ecmascript2020-support/)

`Page not found` now, maybe they will revert this too.

**Comment by AroKol78** [comment]
now I don't even see any bugs in the console (csp warning exception)
and github is still not working properly

**Comment by JustOff** [comment]
Well, the blog post remained in the cache:

![firefox_2022-02-11_00-37-22](https://user-images.githubusercontent.com/340855/153508596-f05c2aa6-9585-4505-aa94-b6a66143bc5d.png)

**Comment by linuxrocks123** [comment]
Maybe you could fix it by intercepting the http requests where they get their JavaScript libraries and replacing them with the old ones from before the change?

**Comment by Vangelis66** [comment]
[Deprecation Notice for ECMAScript2020 Support](https://github.blog/changelog/2022-02-10-deperecation-notice-for-ecmascript2020-support/)

... While these "competent" M$ coders are sorting their English spelling mistakes ("2022-02-10-dep**e**recation-notice-for-ecmascript2020-support/"), they now claim they "haven't written that blog post yet": 

![deperacation](https://user-images.githubusercontent.com/9669492/153506481-b1359bd3-50d8-4006-80f1-080959d7d723.jpg)

Edit: SeaWater beat me to it :smile: 

Slightly OT :wink: : 
Users of official UXP browsers/SM/WF-Classic on **Win7+** still have the option of using an ECMAScript2020-compliant browser, if **only for GitHub**; but M$ have dealt the most severe blow to the **retrocomputing** communities (e.g. XP/Vista users), of which the OP is a member (and partly myself, on my older - but favourite - laptop) ... 
Chromium [79/]**80** was the version where "?." was first implemented, there exist very few (mostly Chinese) forks based on Ch >=79 that can run on XP/Vista; @AroKol78 : I'm now posting this on 360EEv1**3**[Ch86 based], the very **LAST** 360EE version that will run on XP/Vista x86) - it mostly works, but is heavy on resources, especially on older H/W... 

> This means that our chances for a workaround tend to zero.

Apologies in advance if what I suggest is infeasible, but can't we do a search-and-replace "job" for "*?." syntaxes, like the one that got us **GitLab** back in the UXP platform?

**Comment by SeaHOH** [comment]
> Apologies in advance if what I suggest is infeasible, but can't we do a search-and-replace "job" for "*?." syntaxes, like the one that got us **GitLab** back in the UXP platform?

We can't, babel transform is needed.

**Comment by JustOff** [comment]
Thanks to everyone for your ideas about possible methods of combating new changes, but unfortunately at the moment none of them is suitable. Perhaps the integrated Babel processing could be a solution, but it is too difficult to implement and I'm not sure that it's worth the effort.

**Comment by Symbian9** [comment]
Sadly, there is no results in Google WebCache or even Web Archive:

- http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fgithub.blog%2Fchangelog%2F2022-02-10-deperecation-notice-for-ecmascript2020-support%2F
- https://github.blog/changelog/2022-02-10-deperecation-notice-for-ecmascript2020-support/

But Twitter in same time still can parse *website card*:

![Twitter screenshot](https://i.ibb.co/YRdcpf4/Screenshot-2022-02-11-01-47-25.png)

**Comment by dirkf** [comment]
>Maybe you could fix it by intercepting the http requests where they get their JavaScript libraries and replacing them with the old ones from before the change?

Foolishly I forgot to save them. Did anyone in fact do so? ISTR an extension that would allow you force a site to load its resources from a local cache, not one of @JustOff's though?

**Comment by dirkf** [comment]
Of course, editing a post is one of the broken functions.

It may well be that it's actually almost as easy/difficult to bastardise the XUL browsers with this feature rather than work-around it for a specific case.

**Comment by dirkf** [comment]
My high-level contact says that the deprecation post was "a mistake" and the browser support policy is still being reviewed.

Today's breakage is weird because the JS still appears to be reverted, no errors in the console, the [quoted fragment](https://github.com/JustOff/github-wc-polyfill/issues/43#issuecomment-1034676421) is the non-chained version, but the original breakage is back, possibly on all unsupported browsers?

Apparently this extension isn't the problem either, although if we diagnosed the current issue properly it might be amenable to fixing with the extension unlike the optional chaining issue itself.

The cockup-theorist in me would like to hypothesise that those in the GH build team whose ambition is to ensure that the site only works with a browser whose major version has 3 digits are not really getting the message.

**Comment by linuxrocks123** [comment]
If they unbreak it long enough for someone to download the unbroken JavaScript, I expect it should be possible to modify the extension to use said unbroken JavaScript.  It would certainly be worth downloading it just in case.  I'll try to download it if it gets unbroken for me again, but fancy web dev isn't really my thing, so I'd suggest not relying on me to do that.

**Comment by FakelsHub** [comment]
Fucking Microsoft!

**Comment by rofl0r** [comment]
the new breakage without any output in js console is highly suspicious. it's almost as if the JS was tweaked especially to no longer work with palemoon.

**Comment by Symbian9** [comment]
- https://support.github.com/ticket/personal/0/1499112
> ### Ticket not found
>
> The ticket either does not exist or you no longer have access to it.

@dirkf, If you would get some feedback, please post screens too.

**Comment by rubyFeedback** [comment]
>  it's almost as if the JS was tweaked especially to no longer work with palemoon

I think the larger goal is to suppor tonly the chromium code base. I am having problems in
firefox as well recently with github.

**Comment by JustOff** [comment]
Let me repeat, that at the moment even Firefox 78 ESR (which supports most of the ECMAScript2020 features, including the optional chaining operator) does not work properly with GitHub. And while there are no errors in the console, it is not possible to find the cause.

**Comment by dirkf** [comment]
So we need this: https://github.com/ungap/promise-any/blob/master/index.js ?

I applied this as a NoScript surrogate for `<github.githubassets.com` with success (joining a `Promise.AllSettled()` that may or may not be needed now):
```
if (!('any' in Promise.prototype))
    Promise.any = function ($) {
        return new Promise(function (D, E, A, L) {
            A = [];
            L = $.map(function ($, i) {
              return Promise.resolve($).then(D, function (O) {
                  return ((A[i] = O), --L) || E({errors: A});
              });
            }).length;
        });
    }
```

**Comment by JustOff** [comment]
I somehow managed to make GitHub [work again](https://github.com/JustOff/github-wc-polyfill/releases/tag/1.2.10), at least the main functionality. However, it was unlikely to last long.

**Comment by Vangelis66** [comment]
> > As a demonstration, see the https://github.com/JustOff/github-wc-polyfill/issues/43#issuecomment-1035861794.
> 
> That comment is hidden because the ticket is visible only to its author.

Yes, you are correct, but @dirkf probably intended to link [this](https://github.com/JustOff/github-wc-polyfill/issues/43#issuecomment-1035861794) hidden/minified comment of his :wink: 

Your fix was tested to function as intended in latest **Serpent 52**, congrats! :tada: 
BTW, can a JS guru among you translate the "fix" in https://github.com/JustOff/github-wc-polyfill/commit/17b52b6027472e5002dfef8a0607acf2dca80427 to a Userscript format I could install in Violentmonkey and regain GH usability in a Chromium 78 fork? Many thanks :smile:

**Comment by SeaHOH** [comment]
The polyfill `Promise.any` works well with current GH js.

**Comment by SeaHOH** [comment]
Babel transform/rewrite is too heavy, the full javascripts are much bigger.

**Comment by JustOff** [comment]
Well, here is [github-wc-polyfill-1.2.11b1.xpi](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.10/github-wc-polyfill-1.2.11b1.xpi) which implements `Promise.any` polyfill instead of replacing `environment-*.js`.

**Comment by SeaHOH** [comment]
> > Babel transform/rewrite is too heavy, the full javascripts are much bigger.
> 
> too heavy for whom? megabyte-big scripts are the norm, not the exception these days. it would certainly have a performance impact, but the plugin/addon could allow to toggle this on/off on a per-site granularity. so you can at least get misbehaving sites like godbolt or github to work.

Time. you need more time to transform all javascript, and deal many cases how to load them.

**Comment by dirkf** [comment]
> as far as _automitcally fixing any such issues in the future is concerned_ : https://babel.dev/docs/en/babel-standalone
> babel features a standalone js (weighing at 2MB minified, 4MB readable) which appears to be quite straight-forward to use. it looks as if an astute browser plugin hacker could turn this easily into a a separate addon that automatically rewrites all incoming js.

This would be fine in a server-side deployment, where it would be run each time the site JS is deployed to generate the JS that would be served for that site version, and in fact is what sites like GH do or ought to do, or used to when IE was a thing. I doubt that performance would be acceptable if every script from a site was being processed so some caching tactic would be needed that might vary for each site. Again, perhaps better to use effort "up"grading the browser's JS engine.

**Comment by SeaHOH** [comment]
> This would be fine in a server-side deployment

That is very esay to them, but ...

**Comment by rofl0r** [comment]
btw, the youtube series mentioned earlier in this thread  (starting with https://youtu.be/QTm-fqPzjY8 ) is highly interesting, as the guy is hacking on a firefox-style browser using the same concepts as palemoon (IDL files, cpp implementation) implements a couple of things from the html spec regarding to js DOM elements, and it appears to be relatively simple, mostly copy/pasting the spec from MDN and then just turn each step into a line of code.

**Comment by garoto** [comment]
> guy is hacking on a firefox-style browser [...]

Their browser and related "web" engines are written from scratch, which I imagine can be a perk when you don't have to deal with 25+ years of cargo-cult browser code.

**Comment by linuxrocks123** [comment]
I'm still using the old polyfill, and it's working for me right now.  I think they reverted whatever change they made that broke things.

**Comment by JustOff** [comment]
@linuxrocks123 
In fact you are right, at the moment GitHub started to serve [environment.js](https://github.githubassets.com/assets/environment-be47ed29.js) which includes `Promise.any` polyfill, so `github-wc-polyfill` 1.2.**9** also works ;)

**Comment by dirkf** [comment]
GitHub Support wrote:
>We have deployed a change today that should improve functionality on older and 
unsupported browsers.

**Comment by JustOff** [comment]
Perhaps I'll take a break until Monday before I release any updates, while both 1.2.9, 1.2.10 and 1.2.11b1 work.

**Comment by garoto** [comment]
Perhaps might be pertinent to mention to those browsing this issue and unware, when github started breaking with "legacy browsers" like Palemoon around a ~couple years ago perhaps, moonwolf|palewolf|wolfbeast was raising issues with GH all the time, and it happened that they would revert or serve a different js framework based on the UA for a while.

It eventually stopped working alltogether, hence this repo.

**Comment by AroKol78** [comment]
Thanks to JustOff and everyone else involved in solving the problem.
(I will be using/testing 1.2.11b1.)

**Comment by AroKol78** [comment]
again
I checked, don't work: editing comments/previw, buttons Show more activity", profile menu
```
Error: TypeError: (intermediate value).attachShadow is not a function
Source File: https://github.githubassets.com/assets/chunk-index2-a8e52977.js
Line: 1
```
