### ISSUE TITLE
GitHub: "Load diff" misplaced and non-clickable on many commits

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#46]
Browser: **Serpent** v52.9.0 (2022-**01**-**19**) (32-bit) 
[it's platform should be on par with last official **Basilisk 52.9.2022.01.27** (64-bit)]
Extension version: github-wc-polyfill-v1.12.1**3**

STR:

Load, e.g. , https://github.com/JustOff/github-wc-polyfill/commit/3c2384bd098cf2b06429de9d2a49c664855f4ec7: 

![st-ld](https://user-images.githubusercontent.com/9669492/154777866-d1461f34-7a1b-4b88-9a8a-5ef761f2b8d4.JPG)

`Load diff` is **misplaced** (but this is something **already pointed out** [here](https://github.com/JustOff/github-wc-polyfill/issues/44#issuecomment-1043175624)) :wink: , but is also overlaid with the message: 
> Some generated files are **not** rendered by default. [Learn more](https://docs.github.com/github/administering-a-repository/customizing-how-changed-files-appear-on-github).

Sadly, it appears that now you can **only click on either "L" or "o"** (of the whole `Load diff` string) to display the actual commit content, but those two letters are superimposed by the word "**not**" :disappointed: ... 
The screenshot is from a dirty profile, but I have replicated the issue on a **fresh** St52 profile, with only said extension installed...

Toying a little with **uBlock Origin 1.16.4.30**, I removed the overlay with 
`github.com##.width-full.height-full.left-0.top-0.position-absolute.flex-justify-center.flex-items-center.d-flex` and I thus got: 

![st-ld-2](https://user-images.githubusercontent.com/9669492/154778844-1e2c9a69-ba0e-4dee-a96c-2a791a4d6791.JPG)

which now **allows me to generate the diff by clicking on the "Lo" area**, but after **a tab reload**, `Load diff` appears **greyed-out** and **non-clickable**: 

![st-ld-3](https://user-images.githubusercontent.com/9669492/154779101-8f7e5a56-71f1-4f3b-9e62-31295e532edb.JPG)

I have to disable `uBO` on `github.com`, **reload the tab a second time** to get a non-clickable "Lo" area (due to the overlay), then re-enable `uBO` and **reload the tab a third time** to get a clickable "Lo" area (without the overlay); this is impractical ...  

My instinct tells me this issue is caused by limitations in UXP's CSS/JS parsers (can't handle well the CSS code served by GitHub), so I'm not certain it could be addressed in the extension itself, but it sure is a nuisance... :angry: 

Any tips to mitigate the issue (e.g., some userstyle installable in Stylem/Stylus?) would be highly appreciated!

FWIW, this is how things look on a Chromium-**78**-based browser: 

![ch78-ld](https://user-images.githubusercontent.com/9669492/154779445-d2d6d885-ed7f-4c17-93dd-5d6f075f57d3.JPG)

... but this is no surprise, the modern web is tailored to perfectly suit only Chromium (I consider current Firefox to be just another Chromium fork, give or take...). 

As always, utmost gratitude extended to the maintainer of this extension for his unwavering efforts, especially considering current RL tensions in his neck of the woods :heart: ...

**Comment by SeaHOH** [comment]
Your rule is not suitable (big range), MUST only use the unique class name.

    github.com##.hidden-diff-reason

**Comment by JustOff** [comment]
Try [1.2.14b1](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.13/github-wc-polyfill-1.2.14b1.xpi).

**Comment by SeaHOH** [comment]
The button (`.load-diff-button`) got an atttribute `disabled` when reload pages after be clicked.
![disabled-button](https://user-images.githubusercontent.com/8470820/154822585-94cdf259-1ffd-45fc-b7d3-0ed4191c809f.png)

**Comment by Vangelis66** [comment]
Apologies for the tardy replies... :wink: 

> Your rule is not suitable (big range), MUST only use the unique class name.
>
> ```CSS
>github.com##.hidden-diff-reason
>```

... As you'd probably imagine, the `uBO` rule I used and mentioned in my original post was not hand-written, but rather the result of using the built-in **element picker**... 
BTW, I did try your code above, thanks, but arrived in the same results as the ones detailed in my original post (with regards to reloading the tab) ... 

> Try [1.2.14b1](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.13/github-wc-polyfill-1.2.14b1.xpi).

Many thanks for trying to address this :+1: ; I just finished a set of tests (**fresh St52** profile with only `1.2.14b1` installed) and...

1. The **misplacement** issue is correctly mitigated :+1: , see below: 

![P1](https://user-images.githubusercontent.com/9669492/154823076-ba00e6a8-16f9-4a2c-b12e-975f92dcc45a.JPG)

2. However, you can now load the diff by even clicking on the "blue-lined" area (header?), which means the collapse (top left) and ellipsis (top right) buttons can't be accessed without loading diff... 

3. Loading the diff works fine, as do now the two previously mentioned buttons: 

![P2](https://user-images.githubusercontent.com/9669492/154823342-2a489607-cbb8-48d2-baf9-366893356806.JPG)

4. Sadly, once **you reload the tab/page**, the `Load diff` string becomes greyed-out and **non-clickable**, and the latter becomes also true for the "header"/buttons area (red-lined) :cry: : 

![P3](https://user-images.githubusercontent.com/9669492/154823421-cd0cd1dd-4d9b-4856-af83-9c8efe8e0648.JPG)

This last "status" is only resolved by **fully restarting the browser**, as mere tab-reloads/ browser-cache-purging tried here to no avail... :disappointed: 

Hopefully, we're close to a definitive solution!
Best regards :smile:

**Comment by SeaHOH** [comment]
> This last "status" is only resolved by **fully restarting the browser**, as mere tab-reloads/ browser-cache-purging tried here to no avail... disappointed

Reload skip cache be activated with <kbd>Ctrl + Shift + R</kbd>.

**Comment by rofl0r** [comment]
funny, i'm seeing this too in palemoon 29.4.4 with gh polyfill 1.2.13 on this link https://github.com/ryanmcgrath/svgalib-1/commit/e698d8c11f938bb6039a1791dc54c620c228d308

**Comment by SeaHOH** [comment]
It also happen with 1.2.12. Maybe the bug(?)/feature of page status keeping.

**Comment by JustOff** [comment]
> the collapse (top left) and ellipsis (top right) buttons can't be accessed without loading diff...

Try [1.2.14b2](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.13/github-wc-polyfill-1.2.14b2.xpi).

>  once you reload the tab/page, the Load diff string becomes greyed-out and non-clickable

I have no idea how to address this, fortunately, as mentioned above, <kbd>Ctrl + Shift + R</kbd> works.

**Comment by SeaHOH** [comment]
I has tested the old style [frameworks-56f7ce131f05e8b45ad6787fd4b122c3](https://github.githubassets.com/assets/frameworks-56f7ce131f05e8b45ad6787fd4b122c3.css), no issues.

**Comment by THEtomaso** [comment]
Does this uBO rule fix the issue?:
`github.com##.js-diff-entry-loader:style(position: inherit !important;)`

**Comment by garoto** [comment]
> Does this uBO rule fix the issue?: `github.com##.js-diff-entry-loader:style(position: inherit !important;)`

It does for me while using v1.2.13 found on the releases page.

**Comment by Vangelis66** [comment]
> **funny**, i'm seeing this too in palemoon **29.4.4** with gh polyfill **1.2.13**

Why do you find it "funny"? :smiley: **Pale Moon** (that's how its authors like it to be spelt :stuck_out_tongue_winking_eye:) is a UXP-based browser, **Serpent 52** (a forked Basilisk) is built on a **forked UXP** which, to the best of my knowledge, bears no differences to upstream UXP as far as JS/CSS parsers are involved...

> Does this uBO rule fix the issue?:
> ```css
> github.com##.js-diff-entry-loader:style(position: inherit !important;)
>```

It surely **does fix the misplacement** :+1:, with or **without** `github-wc-polyfill-1.2.13` installed (but without this extension, clicking on `Load diff` does nothing, of course...). 

>> the collapse (top left) and ellipsis (top right) buttons can't be accessed without loading diff...
> 
> Try [1.2.14b2](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.13/github-wc-polyfill-1.2.14b2.xpi).

Thanks! :+1: ; That solves it! :tada: 

> I have no idea how to address this, fortunately, as mentioned above, `Ctrl + Shift + R` and `Ctrl + F5` work

... Sad to hear :cry: ... I'll leave this issue open for a tad longer, in the hope some bright idea :bulb: comes up to someone, baring that, **keyboard shortcut**(s) it will be... :wink: 

Best wishes!

**Comment by THEtomaso** [comment]
It should be possible to add a fix, similar to the uBO rule which I posted, to the extension itself.

**Comment by JustOff** [comment]
In fact, your rule is pretty much the same as the one contained in 1.2.14b1:
```css
.js-diff-load-container .js-diff-entry-loader {
  position: inherit !important;
}
```
and here is an addition fix from 1.2.14b2:
```css
.js-skip-tagsearch > .load-diff-button, .js-skip-tagsearch > div {
  height: 75% !important;
  top: 25% !important;
}
```

**Comment by THEtomaso** [comment]
> your rule is pretty much the same as the one contained in 1.2.14b1

Oh, so the remaining issue is that the fix included in your extension breaks upon page refresh?

**Comment by SeaHOH** [comment]
> Is that what you've now addressed in v1.2.14b2?

Big button overlay the commit box's header. https://github.com/JustOff/github-wc-polyfill/issues/46#issuecomment-1046129969

**Comment by SeaHOH** [comment]
This injected script is working.
```javascript
(function () {
  // Remove "disabled" attribute of "Load diff" buttons
  function removeDisabled() {
    for (let button of document.getElementsByClassName('load-diff-button'))
      button.removeAttribute("disabled");
  }
  document.addEventListener('DOMContentLoaded', removeDisabled, {once: true});
  document.addEventListener('pjax:end', removeDisabled);
}());
```

**Comment by misteuk** [comment]
I fix in #48

**Comment by Vangelis66** [comment]
> This injected script is working.

Many thanks, but **where exactly** inside `1.2.14b2`'s **bootstrap.js** file (i.e. between which lines) should this be inserted? Can you submit a proper PR here? 

I have already tried the [very latest commit of your fork](https://github.com/SeaHOH/github-wc-polyfill/commit/c9aa4d3) and it **addresses fully all aspects of this issue** 👍 , but your fork has diverged **significantly** from this ("upstream") to let a non-coder such as I easily apply your posted fix... 
Hopefully **JustOff** will accommodate, when his RL permits... 😃

**Comment by Vangelis66** [comment]
> I have already tried the [very latest commit of your fork](https://github.com/SeaHOH/github-wc-polyfill/commit/c9aa4d3) and it addresses fully all aspects of this issue 👍

@SeaHOH : I just stumbled on a very minor bug of `SeaHOH-gh-wc-polyfill-1.2.14`, which is selectively manifested in this very issue page, i.e. 

1. Load in a tab 
https://github.com/JustOff/github-wc-polyfill/issues/46
2. With the `END` button (or with the scrollbar) go to the very end of the page
3. Reload the tab
4. Once the page has fully reloaded, you now find yourself not at the bottom of the page (expected behaviour), but somewhere in the middle of first (mine) post: 

![bug](https://user-images.githubusercontent.com/9669492/155043212-c3c471f9-1c88-48bc-8890-2a99f478938e.JPG)

This small "bug" isn't there with both `1.2.14b2` or `1.2.13+PR#48` ... 😉

**Comment by SeaHOH** [comment]
> I just stumbled on a very minor bug of `SeaHOH-gh-wc-polyfill-1.2.14`, which is selectively manifested in this very issue page, i.e.

Sorry, I have no idea, I can't reproduce it with my browser.

**Comment by JustOff** [comment]
> when his RL permits...

Unfortunately, it's highly unlikely this will ever happen :-(

**Comment by Vangelis66** [comment]
I can only speak for myself 😉 , since this extension has a very varied user base, but what is of paramount importance now is the safety/well-being of you, your family, your close-ones, etc,, under war conditions... 

I'm afraid this isn't the right place to discuss international politics (and I believe GH doesn't allow this, in any case...), but you've done so much over the course of time 👍 with this extension, in essence providing crutches to browser platforms that can't be put up to the challenges imposed by GitHub by the browser maintainers themselves 😞 ... 

Hopefully, when all dust has settled, you'll be able to revisit/address the 'disabled attribute of  the "Load diff" button'; keep safe, many thanks, again, for all your work thus far! 🥇 ❤️

**Comment by Vangelis66** [comment]
>> This injected script is working.
> 
> where exactly inside [1.2.14b2](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.13/github-wc-polyfill-1.2.14b2.xpi)'s **bootstrap.js** file (i.e. between which lines) should this be inserted?

With no clue myself, I ended up transforming that into a GM/VM **userscript**, 
```js
// ==UserScript==
// @name        Fix disabled "Load diff" button
// @namespace   https://github.com/SeaHOH
// @description Restores disabled "Load diff" area, after it has been clicked once and page reloaded (see https://github.com/JustOff/github-wc-polyfill/issues/46#issuecomment-1046129969).
// @author      SeaHOH
// @include     /^https:\/\/github\.com\/.*\/.*\/pull/
// @include     /^https:\/\/github\.com\/.*\/.*\/commit/
// @run-at      document-start
// @grant       none
// @version     0.1
// @icon        https://github.githubassets.com/pinned-octocat.svg
// ==/UserScript==

(function() {
  // Remove "disabled" attribute of "Load diff" buttons
  document.addEventListener('DOMContentLoaded', function() {
    for (let button of document.getElementsByClassName('load-diff-button'))
      button.removeAttribute("disabled");
  }, {
    once: true
  });
}());
```
... which I'm using together with "github-wc-polyfill-v1.2.14b**2**" in latest **Serpent 52.9.0**; 
works OK; thanks @SeaHOH 👍

**Comment by rofl0r** [comment]
someone with some skills can take @JustOff's last release (1.2.14b2), unzip it and apply the above patch to it and make it available for folks here please ?

**Comment by THEtomaso** [comment]
Be safe, JustOff.

**Comment by AroKol78** [comment]
> (and I believe GH doesn't allow this, in any case)

`https://github.com/github/feedback/discussions/12042`

> Stay safe, JustOff.

and everyone 🇺🇦

**Comment by Vangelis66** [comment]
>> (and I believe GH doesn't allow this, in any case)
> 
> https://github.com/github/feedback/discussions/12042

FWIW, 
https://docs.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed
😕

**Comment by AroKol78** [comment]
https://github.blog/2022-03-02-our-response-to-the-war-in-ukraine/
