### ISSUE TITLE
"Copy the full SHA" no longer works...

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#49]
Platform: (forked) **UXP**
Browser: (latest) **Serpent** 52.9.0 (2022-02-25) (32-bit)
Extension version: **1.2.14b2**
Browser profile: Fresh (with default settings), with only this extension installed

STR:
1. Visit/load e.g. :

https://github.com/JustOff/github-wc-polyfill/commits/master

2. Move cursor to the "**Copy the full SHA**" button of top commit, 

![CopySHA](https://user-images.githubusercontent.com/9669492/156035207-e01852d2-82ce-4fc1-ade8-4b930d9bbcae.jpg)

, **click** button

3. Expected behaviour: Full (**40** chars) commit HASH copied to the clipboard (with a visual indication of a successful copy action)

4. Actual result: Clipboard is **empty** (or contains whatever string was put there, via whatever, immediately previous, copy action)...

5. In contrast, on a **Chromium**-based browser sanctioned by GitHub, this is the visual result of clicking the button in question: 

![CopySHA2](https://user-images.githubusercontent.com/9669492/156036430-68807022-30f2-42e5-af0d-c59e2a673f3b.jpg)

and the clipboard becomes populated with `1291c0573ddaa116c48386110ffe5c6a4fe751a3` ...
Nothing I could spot stands out in Web/Error Console... :disappointed:

**Comment by dirkf** [comment]
Confirm in SM 2.5.10.2.

**Comment by SeaHOH** [comment]
`EventTarget.addEventListener` failed on Custom Elements polyfill.

This code is working:

```javascript
(function () {
  function addEventListener (type, listener, options) {
    const target = this, key = [target, type],
          ael = EventTarget.prototype.addEventListener;
    if (!EVENTS.has(key))
      EVENTS.set(key, function (e) {target.dispatchEvent(new Event(type))});
    ael.call(target, type, listener, options);
    return ael.call(target.parentNode, type, EVENTS.get(key), options);
  }
  function removeEventListener (type, listener, options) {
    const target = this, key = [target, type],
          rel = EventTarget.prototype.removeEventListener;
    rel.call(target, type, listener, options);
    return rel.call(target.parentNode, type, EVENTS.get(key), options);
  }
  const oldCED = customElements.define, EVENTS = new Map();
  customElements.define = function (name, cls) {
    cls.prototype.addEventListener = addEventListener;
    cls.prototype.removeEventListener = removeEventListener;
    oldCED.call(customElements, name, cls);
  };
}());
```

**Comment by Vangelis66** [comment]
I tested the latest snapshot, [`c2f2c72`](https://github.com/SeaHOH/github-wc-polyfill/commit/c2f2c7251e966eb5f9493ce924a79850d0a268ed), of your fork and it does address successfully this issue, thanks 👍 , but... 
Can you please submit a **proper PR** for this **here**, that can cleanly apply on top of **master** branch (or a "patch" on top of **latest beta**, 1.2.**14b2**) ? 
(FWIW, you were kindly invited to do the same for [another](https://github.com/JustOff/github-wc-polyfill/issues/46#issuecomment-1046491551) of your "fixes", but so far you seem reluctant to indulge... ).
Using a **UXP-based** browser myself, I have the "luxury" of being able to try your own fork, but **this** original extension does also cater to **SeaMonkey** users, which are NOT covered, AFAICS, by your fork... 

Kindest regards 😄

**Comment by SeaHOH** [comment]
I will tell you how to patch github-wc-polyfill, so I spend some time on writing digest tool.

<details>
  <summary>Click here to expand and see tool's UI</summary>

![digest tool](https://user-images.githubusercontent.com/8470820/156357540-5610a95c-e044-443a-ab01-578216dfc5fb.png)

</details>

First, copy this html tool to your disk, named e.g. `digest.html`, then load it with your browser.

<details>
  <summary>Click here to expand and copy</summary>

```html
<!DOCTYPE html>
<html lang="en-us">
<head>
<title>Get strings digest integrity</title>
<style>
body > div {
  width: 800px;
  display: block;
  margin: 10px auto;
}
.integrity {
  display: inline-block;
  background: #E0E0E0;
  width: 480px;
  text-align: center;
}
button {
  background: #C0E0FF;
}
</style>
<script>
trimComment = false;
trimWhitespace = true;
async function digest(text) {
  let integrity = "-";
  if (text) {
    let data = new TextEncoder().encode(text),
    hashBuffer = await crypto.subtle.digest('SHA-256', data),
    hashArray = Array.from(new Uint8Array(hashBuffer)),
    hash = btoa(String.fromCharCode(...hashArray));
    integrity = `sha256-${hash}`;
  }
  document.getElementById("integrity").textContent = integrity;
  console.log(integrity);
}
function escape1(text) {
  // escape special replacement patterns
  return text.replace(/\$([$&'1-9])/g, "$\\$1")
             .replace(/\r\n?/g, "\n");         // unify line ending
}
function escape2(text) {
  return text.replace(/`|\\/g, "\\$&")         // escape [`] [\]
             .replace(/\$\{/g, "\\${");        // escape place holder
             
}
function wrap(text) {
  text = escape1(text);
  if (trimComment)
    text = text.replace(/\/\*.+?\*\//sg, "")   // range comment
               .replace(/\s*\/\/.*/g, "");     // standalone comment
  if (trimWhitespace)
    text = text.replace(/^\s*\n/g, "")         // head white
               .replace(/\n\s*(\n|$)/g, "\n")  // empty line
               .replace(/\s*(?=\n|$)/g, "");   // tail white
  text = text.replace(/^\s*$/g, "");           // empty text
  document.getElementById("wrapped").textContent = "`" + escape2(text) + "`";
  return text;
}
async function deal(e) {
  let text = wrap(e.target.value);
  await digest(text);
}
function clipboardCopy(node) {
  let selection = getSelection(),
      range = document.createRange();
  selection.removeAllRanges();
  range.selectNodeContents(node);
  selection.addRange(range);
  document.execCommand('copy');
  selection.removeAllRanges();
}
</script>
</head>
<body>
<div>
  <h3>Input Strings</h3>
  <textarea id="inputstings" rows="20" cols="90" oninput="deal(event)"></textarea>
</div>
<div>
  <h3>Output Digest Integrity</h3>
  <div class="integrity"><b id="integrity">-</b></div>
  <button onclick="clipboardCopy(integrity)">copy integrity</button>
</div>
<div>
  <h3>Output Wrapped Strings</h3>
  <textarea id="wrapped" rows="20" cols="90" disabled="disabled"></textarea>
  <button onclick="clipboardCopy(wrapped)">copy wrapped strings</button>
</div>
<script>
inputstings.dispatchEvent(new Event("input"));
</script>
</body>
</html>
```

</details>

Paste the script who will be injected, into input text area, then you can click buttons to copy the following needed values.
```diff
+++const pfFollowUp = WRAPPED STRINGS;
+++const hashFollowUp = "'DIGEST INTEGRITY'";
```

Add `hashFollowUp` digest integrity.
```diff
---              csp = csp.replace(/script-src /g, "script-src " + hashBase);
+++              csp = csp.replace(/script-src /g, "script-src " + hashBase + " " + hashFollowUp + " ");
```

Inject `pfFollowUp` at first position, in result it's the last.
```diff
      if (this.site == "github") {
+++        data = data.replace("<head>", "<head><script>" + pfFollowUp + "</script>");
```

Remove unnecessary e.g.
```diff
---        data = data.replace(/<script.+chunk-index2-[a-z0-9]+\.js"><\/script>/, "...");
```

**Comment by AroKol78** [comment]
it already works for me (Serpent52 + 1.2.15b1)
