### ISSUE TITLE
Extension won't install out-of-the-box in latest (and last) official Basilisk browser

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#52]
Official **[Basilisk browser](https://www.basilisk-browser.org/)** by MCP is one this extension **natively supports** (along with Pale Moon & Seamonkey);

https://forum.palemoon.org/viewtopic.php?f=61&t=27845
https://www.basilisk-browser.org/releasenotes.shtml
https://www.basilisk-browser.org/download.shtml

The **EoL** binary officially released (64-bit **only**, requires at minimum **Win7 SP1**) has an `appVersion` of `52.9.2022.01.27`, but because of 

https://github.com/JustOff/github-wc-polyfill/blob/0a94bdaecf1e0de77a966ebb64d45fe321225a81/install.rdf#L25

this extension **won't install** there (without manually tinkering with the `install.rdf` file...); thus, `maxVersion` should be now raised to `52.9.2022.*` to allow for such an installation :smile: ...

Kindest regards.

**Comment by SeaHOH** [comment]
So, according to your test, it work well for `52.9.2022.*`?

**Comment by Vangelis66** [comment]
**Basilisk** `v52.9.2022.01.27` is on par with latest **Pale Moon** `v29.4.4`, as far as the underlying **UXP** platform is concerned, so yes; of course, no-one can tell how this EoL build will behave after 6 months or more, but since the previous Basilisk release (`v52.9.2021.12.13`) is still compatible with the extension installation-wise, why should the latest one not be?
If, OTOH, you're asking if a maxVersion of `52.9.2022.*` will allow the extension installation out-of-the-box, then yes...

**Comment by SeaHOH** [comment]
Thanks. The release asset is updated.
BTW, it should be LTS instead of EOF.
