### ISSUE TITLE
[regression]Closed issue #46 seems to have come back...

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#53]
Browser: Latest (UXP-based) **Serpent 52**.9.0 (2022-02-25) (32-bit)
Browser profile: Fresh/clean one (with default settings), only this extension installed
Extension version: Latest release, i.e. v**1.12.15**

![p1](https://user-images.githubusercontent.com/9669492/156955272-b8311436-6df7-4880-b162-096d79aa44cf.JPG)

STR

1. Load in a tab, e.g. [`8446565` (#48)](https://github.com/JustOff/github-wc-polyfill/pull/48/commits/8446565a53543e7c48013039794f6c1fd22f2b78)
2. Click the `Load diff` area; diff will **display correctly** :+1: .
3. Now **normally reload** that same tab; depending on the time of day (i.e. completely random :smile_cat: ), you'll either get a **misplaced and disabled** `Load diff` button like below: 

![p2](https://user-images.githubusercontent.com/9669492/156956062-b6a1def1-944e-4255-aa73-5ebc2efc88f7.JPG)

or a correctly aligned `Load diff` button, but **disabled** nonetheless :angry: :

![p3](https://user-images.githubusercontent.com/9669492/156956189-ed67a900-1951-4afb-97a5-ffd0c0c6ef4e.JPG)

Since we know that the code that addressed #46 is already inside `v1.12.15`, and with me not being a coder in the slightest, I'd hazard a guess that some type of race-condition is taking place that prevents that code from actually functioning... Perhaps it has to be **the last** to run (or is every polyfill inside the extension injected asynchronously?) ? 

As already noted in #46, `CTRL+F5` will, again, restore things...

PS: The [SeaHOH fork](https://github.com/SeaHOH/github-wc-polyfill) is also plagued by the same issue currently (at least for me, that is...).

**Comment by SeaHOH** [comment]
This will be fixed in next release.

**Comment by Vangelis66** [comment]
I tried **latest beta**, [1.2.16b1](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.15/github-wc-polyfill-1.2.16b1.xpi), and in non-exhaustive testing it appears to address **very well** this regression 👍 ; congrats and thanks a bunch 🥇 !
