### ISSUE TITLE
Reaction tooltips missing on "Releases" page / Missing tooltips for Editor's toolbar buttons 

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#54]
Browser: Latest (**UXP**-based) **Serpent 52**.9.0 (2022-02-25) (32-bit)
Browser profile: **Fresh**/clean one (with default settings), only this extension installed
Extension version: Latest release, i.e. v**1.12.15**

STR

1. Make sure **you're already signed-in**, as this GitHub feature is reserved for GitHub members...
2. Load e.g. https://github.com/SeaHOH/github-wc-polyfill/releases
In the "reactions" area, just below "Assets", you'll see that (at the time of this writing) **6** members have reacted with :+1:  and **another** with a :heart: emoji.
3. Place the cursor on top of either reaction; 
expected behaviour: A **tooltip** containing the **usernames** of the members that reacted similarly: 

![tooltip](https://user-images.githubusercontent.com/9669492/156960563-cd591233-2300-4935-b3fd-02b283280b65.JPG)

(the above was taken with a **Chromium**-derived browser)

actual behaviour: **No tooltip** is being displayed: 

![tooltip2](https://user-images.githubusercontent.com/9669492/156960849-949d38cf-dfc6-4c47-b8d0-885c9b3cf0e4.JPG)

(**St52**+gh-wc-pf-**1.12.15**)

NB: "Reaction" tooltips are being displayed correctly on **Comment** reactions...

**Addendum**: 

It later emerged that the GitHub editor's toolbar buttons are similarly affected, i.e. 

1. Scroll down this page to find the "New Comment" input field (you also need to be **signed-in**). 
2. Hover with the cursor over one of the editor's toolbar buttons, 

![c3](https://user-images.githubusercontent.com/9669492/157126093-fc1f89ef-2f23-4462-8161-ca4f708253bf.JPG)

expected behaviour: A tooltip pops-up, **explaining the function** of selected button: 

![c4](https://user-images.githubusercontent.com/9669492/157126578-db1946be-2bde-4273-9bd2-a373255f0ff7.JPG)

(**Chromium**-derived browser)

actual behaviour: Tooltip missing: 

![c2](https://user-images.githubusercontent.com/9669492/157126738-ceb84ca0-fd06-4ab5-88b3-36765fca9a71.JPG)

(**St52**+gh-wc-pf-**1.12.15**)

**Comment by SeaHOH** [comment]
I can't find the reason. A style as dirty fix is:
```css
.hx_tooltip {
  position: static !important;
  opacity: 1 !important;
}
```

**Comment by AroKol78** [comment]
for uBo
`github.com##.hx_tooltip:style(opacity: 1 !important;)`
or (a little different effect)
`github.com##.hx_tooltip:style(position: static !important; opacity: 1 !important;)`

**Comment by Vangelis66** [comment]
Thanks for investigating this 👍 ; I still hope a proper solution will present itself in due course... 😉 

> for uBO: 
> ```css
> github.com##.hx_tooltip:style(position: static !important; opacity: 1 !important;)
> ```

Unfortunately, **that one**, as well as the **CSS style** proposed by **SeaHOH** do also affect other GH regions, e.g. the position of tooltips that pop-up when hovering over the **comment editor's toolbar buttons**:  

![C1](https://user-images.githubusercontent.com/9669492/157122437-6bc6f7cb-a05e-4293-8f37-1b5958d07b5b.JPG)

which, I have come to realise now, are also **plagued by that very same bug** 😠 ...

**Comment by Vangelis66** [comment]
**First** post, as well as issue's **title** have been updated...

**Comment by SeaHOH** [comment]
Is this more better?
```css
markdown-toolbar > div, .js-pick-reaction > div {
  position: relative !important;
}
.hx_tooltip {
  opacity: 1 !important;
  bottom: 110% !important;
  left: 0 !important;
}
```

**Comment by AroKol78** [comment]
it's OK
<details><summary>pic1:</summary>

![isokgh001](https://user-images.githubusercontent.com/70756447/157276740-aedbcc4d-b200-42b4-98cf-9e36e86a1772.PNG)

</details>

**Comment by Vangelis66** [comment]
> Is this more better?

It certainly is a compromise one could live with... :+1: :smile: 

FTR, in **Chromium** every button in the editor's toolbar **spawns its own tooltip** when hovered, displayed slightly **below** said button (see opening post, 4th attached screenshot); with that latest **userstyle**, every 3 successive buttons, starting from left to right (1-3, 4-6, 7-9, 10-12), share the **same tooltip position**, displayed slightly above the button(s) ... 

As for **Releases reaction tooltips**, these are now displayed **above** the emojis, which is closer to what **Chromium** does... :+1: 

At the end of the day, without me nitpicking :stuck_out_tongue_winking_eye: , **all required information** (provided by the tooltips) is indeed displayed in an acceptable fashion, so, unless somebody has an "epiphany" **on the actual root cause of this bug in UXP**, "we" could settle for such a CSS workaround... 
Many thanks!

**Comment by SeaHOH** [comment]
[github-wc-polyfill-1.2.16b2](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.15/github-wc-polyfill-1.2.16b2.xpi)
I caught it, an attribute issue by named `hidden`.

**Comment by Vangelis66** [comment]
> I caught it, an attribute issue by named `hidden`

👍 🥇 🎉 🚀 : 

![F2](https://user-images.githubusercontent.com/9669492/157463335-b5eb387f-b12b-4359-ab22-d4a4a5aa113a.JPG)

![F1](https://user-images.githubusercontent.com/9669492/157463454-c616d0ca-5823-47a0-a3e7-9e90da5a1a37.JPG)

(**St52**+gh-wc-pf-**1.2.16b2**)

... Someone did have an epiphany, for sure! 😄 
Closing this, thanks...

**Comment by Vangelis66** [comment]
> when **deleting an earlier comment** (ST52 + 1.2.16)

I can replicate 👍 :

![b1](https://user-images.githubusercontent.com/9669492/157789845-72c24643-964b-4da1-82b4-fd24674cc5c6.JPG)

; but why do you think it's related to this **closed** issue? 
I get **the same** result with `1.2.16b1`, too, which doesn't contain the "fix" for #54 ...

Additionally, when I actually **delete** a comment **revision**, the **whole webpage reloads** 😠 ; not sure whether it's a **bug** or **intended behaviour**... 
How do **latest** Chrome/Firefox act in that regard (I can't test in this laptop now...) ?
If they do it **differently**, perhaps I (or someone else 😜 ) should file a **new**, separate, **issue** ...

**Comment by AroKol78** [comment]
it just gives a signal that something like that is (i don't even know if it's specific to UXP only)

**Comment by Vangelis66** [comment]
I know the extension has been abandoned now, however, for clarity reasons, this original issue has, as of the **first week of Aug 2022**, come back now :rage:, involving ALL **GH** tooltips, i.e. both the **Editor's toolbar buttons** as well as **reaction tooltips** on comments/releases...

Anyone willing to take a look, please chime in... 😉

**Comment by Vangelis66** [comment]
The issue has been successfully resolved a second time, by @roytam1, by backporting fixes from the currently maintained fork, `palefill` 🎉 ...
For the updated source code, look at: 
https://github.com/roytam1/github-wc-polyfill/commit/1a0d796a8a63497edea54e4baea56cb4dfda6e71
For compiled source, i.e. an .XPI file, look [here](https://github.com/JustOff/github-wc-polyfill/issues/68#issuecomment-1218104421) 👍 .

Many thanks to all the devs (**roytam1**, **SeaHOH**, **martok**) involved! ❤️
