### ISSUE TITLE
Extension breaks on GitHub "404" pages...

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#55]
Browser: Latest (**UXP**-based) **Serpent 52**.9.0 (2022-02-25) (32-bit)
Browser profile: **Fresh**/clean one (with default settings), only this extension installed
Extension version: Latest release, i.e. v**1.12.15**

STR

1. One of my bookmarks is

https://github.com/coletdjnz/yt-dlp-dev/commits/itv-fix

FTR, that URI **did have content** until very recently, when the repo's owner deleted the `itv-fix` branch... 
If you visit that URI now, you'll get a familiar "Page not found" 

> 404 - This is not the web page you are looking for.

result...

2. Try to access your GH account's **avatar button**, on the top-right, e.g. to sign out/change an account setting, etc. 

expected result: The familiar **dropdown** should open: 

![p1](https://user-images.githubusercontent.com/9669492/157131493-15a6a3d4-7a1c-4353-a4c7-a68da8617e6a.JPG)

(**Chromium**-derived browser)

actual result: The **dropdown** informs:

> Sorry, something went wrong.

![p2](https://user-images.githubusercontent.com/9669492/157132021-059ff4fd-2a63-4a56-acf0-b5771a7857d8.jpg)

(**St52**+gh-wc-pf-**1.12.15**)

Errors are shown in Web Console: 
```
TypeError: window.customElements is undefined[Learn More]  vendors-node_modules_github_clipboard-copy-element_dist_index_esm_js-node_modules_github_filt-19a0ad-b0aa79d964b0f0b0715d.js:1:14977
ReferenceError: customElements is not defined[Learn More]  element-registry-f2d13d7793cb74e9c058.js:1:231
TypeError: window.customElements is undefined[Learn More]  behaviors-df903b53ab15748a5077.js:1:4217
TypeError: window.customElements is undefined[Learn More]  vendors-node_modules_delegated-events_dist_index_js-node_modules_github_catalyst_lib_index_js-6e358f-064c9c0434d0fad1cfc8.js:1:8547
```

Thanks for your efforts :+1: , I feel somehow guilty, though, for hitting (and reporting) many bugs recently... :stuck_out_tongue_winking_eye: :smile:

**Comment by AroKol78** [comment]
maybe A/B test
I have not received the error yet, I will probably meet with an error tomorrow
on uxp the engine more and more sites stop working, **...**

**Comment by SeaHOH** [comment]
[github-wc-polyfill-1.2.16b1](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.15/github-wc-polyfill-1.2.16b1.xpi)
The 404 page has not be patched. Try this also for #53 .

**Comment by Vangelis66** [comment]
This **latest beta**, `1.2.16b1`, does address **successfully** 👍 the case of "**404**" GitHub pages; well done! ❤️
