### ISSUE TITLE
Nullish coalescing operator (??) is back, with a vengeance :-(

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/github-wc-polyfill#58]
Browser: Latest (**UXP**-based) **Serpent 52**.9.0 (2022-02-25) (32-bit)
Browser profile: Both **dirty** (current) and **fresh**/clean one (with default settings), only this extension installed
Extension version: Latest release, i.e. v**1.12.16**

Since about three hours ago (ca. 202203111600 UTC), **GitHub** are **again** serving up scripts containing the [Nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator), which is something [they also did in the recent past](https://github.com/JustOff/github-wc-polyfill/issues/44#issuecomment-1059679800), as part of previous, closed, #44 ... :rage: 

https://github.com/JustOff/github-wc-polyfill/issues/56 => 

![e1](https://user-images.githubusercontent.com/9669492/157934415-c98dcf84-d908-4207-8e24-3d7a0331d6b8.jpg)

```
SyntaxError: expected expression, got '?'[Learn More]    8933-d8b0634d2391.js:49:2049
```
`https://github.githubassets.com/assets/8933-d8b0634d2391.js`

From a quick search, areas/functions affected are: 

1. Comment Previews NOT working
2. Names of emojis missing when selecting reaction
3. Actually reacting results in the whole page getting reloaded, ending up in the top of that page
4. ellipsis (`...`) buttons (e.g. in comments list view) are NOT working
5. GitHub favicons on tabs not respecting browser's `browser.display.prefers_color_scheme` **about:config** setting
6. Possibly **many more**, I didn't search thoroughly...

<details>
<summary>OT, but maybe not...</summary>

As in the past, my Chromium 69/78 based, alternative (to UXP), browsers on my platform also broke, typing this now on the **sole** browser (Chromium **86** based) that currently works with GitHub here :disappointed:  ; please, re-think the possibility of hosting this repo on a more browser-agnostic platform... :wink: )
</details>

I don't know whether this is part of another **A/B test**, but I'm already affected myself, being located in South-Eastern Europe... :angry:

**Comment by dirkf** [comment]
Presumably any function that would have loaded after this syntax error is lost.

19:10:29.029 SyntaxError: expected expression, got '?' 8933-d8b0634d2391.js:49:2049

This code is `t=t??""; -> t = (typeof(t) === "undefined" || t === null)? "": t; but in this context probably just changing it to || would be OK.

Also broken: comment edit/hide, but delete is working.

**Comment by Vangelis66** [comment]
Hovering over **issue**/**PR** numbers (links), e.g. #58, also broken...

**Comment by garoto** [comment]
nota bene: do not mark anything as "done" on your Notification feed for the time being.

**Comment by Vangelis66** [comment]
202203120200 UTC: 

The influx of (??) containing scripts appears **to have stopped for me** a short while ago, as a result **GitHub** with `1.2.16` is again **functional** here :tada: ! 
... What the next hours will bring is anyone's guess... 😠

**Comment by SeaHOH** [comment]
I just wake up. So, GH is working now?

**Comment by SeaHOH** [comment]
> additional unusual csp
> 
> ```
> Timestamp: 2022-03-11 20:03:50
> Warning: Content Security Policy: Couldn’t process unknown directive ‘require-trusted-types-for’
> Timestamp: 2022-03-11 20:03:50
> Warning: Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
> ```

@AroKol78 Are they still occur? I need the URL.

**Comment by dirkf** [comment]
No [weirdness](https://github.com/JustOff/github-wc-polyfill/issues/58#issuecomment-1065430686) for me now, SM 2.53.11.

**Comment by AroKol78** [comment]
> Are they still occur? I need the URL.

it doesn't show up anymore, along with the other bugs, fine for now

**Comment by SeaHOH** [comment]
I think they will keep this way for a long time.
