### ISSUE TITLE
Congratulations for this great extension : Thanks to you JustOff, github work back again !

### ISSUE THREAD

**Issue by sebma** [JustOff/github-wc-polyfill#9]
Hi JustOff,

I want to thank you personally for this great extension !
Thanks to you JustOff, github work back again !!
:+1: 
BTW : You can close this issue because it's not a real one :smile: 
God bless you abundantly in all areas of your life.

**Comment by JustOff** [comment]
You are welcome :stuck_out_tongue_winking_eye:
